<?php

declare(strict_types=1);

namespace Setono\CronBuilder;

use PHPUnit\Framework\TestCase;
use Symfony\Component\Finder\Finder;

final class CronBuilderTest extends TestCase
{
    /**
     * @test
     */
    public function it_builds(): void
    {
        $crontab = self::getCronBuilder()->build();

        $expected = <<<CRON
###> Automatically generated by Setono Cron Builder - DO NOT EDIT ###
0 0 * * * /usr/bin/php /home/johndoe/public_html/send-report.php --verbose # Run every day at midnight
###< Automatically generated by Setono Cron Builder - DO NOT EDIT ###

CRON;

        self::assertSame($expected, $crontab);
    }

    /**
     * @test
     */
    public function it_builds_with_prod_env_set(): void
    {
        $crontab = self::getCronBuilder()
            ->addContext('env', 'prod')
            ->build()
        ;

        $expected = <<<CRON
###> Automatically generated by Setono Cron Builder - DO NOT EDIT ###
0 0 * * * /usr/bin/php /home/johndoe/public_html/send-report.php --verbose # Run every day at midnight
0 0 * * * /usr/bin/php /home/johndoe/public_html/process.php --verbose
###< Automatically generated by Setono Cron Builder - DO NOT EDIT ###

CRON;

        self::assertSame($expected, $crontab);
    }

    /**
     * @test
     */
    public function it_merges(): void
    {
        $existingCrontab = <<<CRON


0 0 * * * /usr/bin/php /home/johndoe/public_html/other-job.php

###> Automatically generated by Setono Cron Builder - DO NOT EDIT ###
0 0 * * * /usr/bin/php /home/johndoe/public_html/delete-files.php
###< Automatically generated by Setono Cron Builder - DO NOT EDIT ###




CRON;

        $expected = <<<CRON
0 0 * * * /usr/bin/php /home/johndoe/public_html/other-job.php

###> Automatically generated by Setono Cron Builder - DO NOT EDIT ###
0 0 * * * /usr/bin/php /home/johndoe/public_html/send-report.php --verbose # Run every day at midnight
###< Automatically generated by Setono Cron Builder - DO NOT EDIT ###

CRON;

        self::assertSame($expected, CronBuilder::merge($existingCrontab, self::getCronBuilder()));
    }

    private static function getCronBuilder(): CronBuilder
    {
        return (new CronBuilder())
            ->addFiles((new Finder())->files()->in(__DIR__ . '/cronjobs'))
            ->addContext('release_path', '/home/johndoe/public_html')
            ->addContext('args', ['--verbose'])
        ;
    }
}
