<?php

declare(strict_types=1);

namespace Setono\CronBuilder;

use PHPUnit\Framework\TestCase;
use Setono\CronBuilder\VariableResolver\ExprVariableResolver;

/**
 * @covers \Setono\CronBuilder\CronBuilder
 */
final class CronBuilderTest extends TestCase
{
    /**
     * @test
     */
    public function it_builds(): void
    {
        $cronBuilder = new CronBuilder([
            'source' => __DIR__ . '/cronjobs',
        ]);
        $cronBuilder->addVariableResolver(new ExprVariableResolver());

        $expected = <<<CRON
###> Automatically generated by Setono Cron Builder - Do not edit ###
0 0 * * * php test-script.php
0 0 * * * php test-script.php
0 0 * * * php test-script.php # Executes a great command
0 0 * * * php test-script.php test
###< Automatically generated by Setono Cron Builder - Do not edit ###

CRON;

        $actual = $cronBuilder->build([
            'env' => 'test',
        ]);

        self::assertSame($expected, $actual);
    }
}
