<?php

declare(strict_types=1);

namespace Setono\CronBuilder;

use Twig\Environment;
use Twig\Loader\ArrayLoader;

final class CronBuilder
{
    private readonly Environment $twig;

    private string $delimiter = 'Automatically generated by Setono Cron Builder - DO NOT EDIT';

    /**
     * List of file names with cron job definitions
     *
     * @var list<string>
     */
    private array $files = [];

    /** @var array<string, mixed> */
    private array $context = [];

    public function __construct(Environment $twig = null)
    {
        $this->twig = $twig ?? new Environment(new ArrayLoader());
    }

    /**
     * @param 'begin'|'end' $type
     */
    public function getParsedDelimiter(string $type): string
    {
        if ('begin' === $type) {
            return $this->parse('###> ' . $this->delimiter . ' ###');
        }

        return $this->parse('###< ' . $this->delimiter . ' ###');
    }

    /**
     * @param non-empty-string $delimiter
     */
    public function setDelimiter(string $delimiter): self
    {
        $this->delimiter = $delimiter;

        return $this;
    }

    public function addFile(string|\SplFileInfo $file): self
    {
        if ($file instanceof \SplFileInfo) {
            $file = $file->getPathname();
        }

        if (!file_exists($file)) {
            throw new \InvalidArgumentException(sprintf('The file %s does not exist', $file));
        }

        $this->files[] = $file;

        return $this;
    }

    /**
     * @param iterable<string|\SplFileInfo> $files
     */
    public function addFiles(iterable $files): self
    {
        foreach ($files as $file) {
            $this->addFile($file);
        }

        return $this;
    }

    /**
     * @param array<string, mixed> $context
     */
    public function setContext(array $context): self
    {
        /**
         * @var mixed $value
         */
        foreach ($context as $key => $value) {
            $this->addContext($key, $value);
        }

        return $this;
    }

    public function addContext(string $key, mixed $value): self
    {
        $this->context[$key] = $value;

        return $this;
    }

    /**
     * Returns a valid crontab string
     */
    public function build(): string
    {
        $crontab = '';

        foreach ($this->files as $file) {
            /**
             * @psalm-suppress UnresolvableInclude
             *
             * @var mixed $definition
             */
            $definition = require $file;

            if (!is_callable($definition)) {
                throw new \InvalidArgumentException(sprintf('The cron jobs definition file %s must return a callable', $file));
            }

            /** @var mixed $cronjobs */
            $cronjobs = $definition($this->context);
            if (!is_iterable($cronjobs)) {
                throw new \InvalidArgumentException(sprintf('The cron jobs definition in %s must return an iterable, got %s', $file, gettype($cronjobs)));
            }

            /** @var mixed $cronjob */
            foreach ($cronjobs as $cronjob) {
                if (!is_object($cronjob)) {
                    throw new \InvalidArgumentException(sprintf('The cron job must be an object, got %s', gettype($cronjob)));
                }

                if (!$cronjob instanceof CronJob) {
                    throw new \InvalidArgumentException(sprintf('The cron job must be an instance of %s, got %s', CronJob::class, $cronjob::class));
                }

                $crontab .= $this->parse($cronjob->toString()) . "\n";
            }
        }

        return sprintf("%s\n%s\n%s", $this->getParsedDelimiter('begin'), rtrim($crontab), $this->getParsedDelimiter('end')) . "\n";
    }

    public static function merge(string $existingCron, self $cronBuilder): string
    {
        $existingCron = trim($existingCron);

        if ('' === $existingCron) {
            return $cronBuilder->build();
        }

        $cron = $cronBuilder->build();

        $replacedCron = preg_replace(
            sprintf(
                '/%s.*%s/ms',
                preg_quote($cronBuilder->getParsedDelimiter('begin'), '/'),
                preg_quote($cronBuilder->getParsedDelimiter('end'), '/'),
            ),
            $cron,
            $existingCron,
            -1,
            $replacements,
        );

        if (0 === $replacements) {
            return $existingCron . "\n" . $cron;
        }

        if (1 === $replacements) {
            return trim($replacedCron) . "\n";
        }

        throw new \RuntimeException('The number of replacements should be 1 or 0');
    }

    private function parse(string $value): string
    {
        return $this->twig->createTemplate($value)->render($this->context);
    }

    private static function scalarToString(mixed $value): string
    {
        if (is_bool($value)) {
            return $value ? '1' : '0';
        }

        return (string) $value;
    }
}
