<?php

declare(strict_types=1);

namespace Setono\CronBuilder;

use Symfony\Component\Finder\Finder;
use Twig\Environment;
use Twig\Loader\ArrayLoader;

final class CronBuilder
{
    private readonly Environment $twig;

    public string $delimiter = 'Automatically generated by Setono Cron Builder - DO NOT EDIT';

    /**
     * List of file names with cron job definitions
     *
     * @var list<string>
     */
    private array $files = [];

    public readonly Context $context;

    /**
     * @param string|list<string> $directories
     */
    public function __construct(string|array $directories = [])
    {
        $this->twig = new Environment(new ArrayLoader());
        $this->context = new Context();

        if (is_string($directories)) {
            $directories = [$directories];
        }

        if ([] !== $directories) {
            $this->addFiles(
                (new Finder())
                    ->files()
                    ->in($directories)
                    ->name('*.php'),
            );
        }
    }

    public function addFile(string|\SplFileInfo $file): self
    {
        if ($file instanceof \SplFileInfo) {
            $file = $file->getPathname();
        }

        if (!file_exists($file)) {
            throw new \InvalidArgumentException(sprintf('The file %s does not exist', $file));
        }

        if (in_array($file, $this->files, true)) {
            return $this;
        }

        $this->files[] = $file;

        return $this;
    }

    /**
     * @param iterable<string|\SplFileInfo> $files
     */
    public function addFiles(iterable $files): self
    {
        foreach ($files as $file) {
            $this->addFile($file);
        }

        return $this;
    }

    /**
     * Returns a valid crontab string
     */
    public function build(): string
    {
        $crontab = '';

        foreach ($this->files as $file) {
            /**
             * @psalm-suppress UnresolvableInclude
             *
             * @var mixed $definition
             */
            $definition = require $file;

            if (!is_callable($definition)) {
                throw new \InvalidArgumentException(sprintf('The cron jobs definition file %s must return a callable', $file));
            }

            /** @var mixed $cronjobs */
            $cronjobs = $definition($this->context);
            if (!is_iterable($cronjobs)) {
                throw new \InvalidArgumentException(sprintf('The cron jobs definition in %s must return an iterable, got %s', $file, gettype($cronjobs)));
            }

            /** @var mixed $cronjob */
            foreach ($cronjobs as $cronjob) {
                if (!is_object($cronjob)) {
                    throw new \InvalidArgumentException(sprintf('The cron job must be an object, got %s', gettype($cronjob)));
                }

                if (!$cronjob instanceof CronJob) {
                    throw new \InvalidArgumentException(sprintf('The cron job must be an instance of %s, got %s', CronJob::class, $cronjob::class));
                }

                $crontab .= $this->parse($cronjob->toString()) . "\n";
            }
        }

        return sprintf("%s\n%s\n%s", $this->getParsedDelimiter('begin'), rtrim($crontab), $this->getParsedDelimiter('end')) . "\n";
    }

    public static function merge(string $existingCron, self $cronBuilder): string
    {
        $existingCron = trim($existingCron);
        $cron = $cronBuilder->build();

        if ('' === $existingCron) {
            return $cron;
        }

        $replacedCron = preg_replace(
            sprintf(
                '/%s.*%s/ms',
                preg_quote($cronBuilder->getParsedDelimiter('begin'), '/'),
                preg_quote($cronBuilder->getParsedDelimiter('end'), '/'),
            ),
            $cron,
            $existingCron,
            -1,
            $replacements,
        );

        if (0 === $replacements) {
            return $existingCron . "\n" . $cron;
        }

        if (1 === $replacements) {
            return trim($replacedCron) . "\n";
        }

        throw new \RuntimeException('The number of replacements should be 1 or 0');
    }

    private function parse(string $value): string
    {
        return $this->twig->createTemplate($value)->render($this->context->toArray());
    }

    /**
     * @param 'begin'|'end' $type
     */
    private function getParsedDelimiter(string $type): string
    {
        if ('begin' === $type) {
            return $this->parse('###> ' . $this->delimiter . ' ###');
        }

        return $this->parse('###< ' . $this->delimiter . ' ###');
    }
}
